server:
  port: 8004

spring:
  application:
    name: dashboard
  cloud:
    config:
      uri: http://127.0.0.1:8003
      name: bootstrap
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/