server:
  port: 8080
  servlet:
    session:
      cookie:
        name: VAP-SESSION
        maxAge: 86400

spring:
  application:
    name: vap-feature
  mvc:
    pathmatch:
      # mvc弱匹配，整合swagger
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
  file:
    path: ./log/${spring.application.name}

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}