server:
  port: 8080
  servlet:
    session:
      cookie:
        name: VAP-SESSION
        maxAge: 204800

spring:
  application:
    name: vap-feature
  mvc:
    pathmatch:
      # mvc弱匹配，整合swagger
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info