server:
  port: 8003

cup:
  schedule:
    is-sync: false

#spring监控管理（访问"/actuator"）
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#去除CONDITIONS EVALUATION REPORT日志信息
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR

spring:
  application:
    name: vaps-cup
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vap?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
  mail:
      host: smtp.163.com
      username: m18857117153@163.com
      password: ling123427
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/



