server:
  port: 8022
  servlet:
    session:
      cookie:
        name: VAPSESSION

spring:
  application:
    name: vaps-vap

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vap?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

  mail:
    host: smtp.163.com
    username: m18857117153@163.com
    password: ling123427
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true

auth-server: http://localhost:9999

security:
  oauth2:
    client:
      registration:
        github:
          client-id: 5cc157387a790c5204e1
          client-secret: d47ea7f5340fc33118f30f691666d9956ce2bcff
        google:
          client-id: 594014553745-c32lehnngg6unckm5299h5hcet2lbfdo.apps.googleusercontent.com
          client-secret: bhtfubUHtrquasO3oUjQultq
        vap:
          client-d: client
          client-secret: 12345

          #    client:
          #      clientId: client
          #      clientSecret: 12345
          #      accessTokenUri: ${auth-server}/oauth/token
          #      userAuthorizationUri: ${auth-server}/oauth/authorize
          #    resource:
          #      userInfoUri: ${auth-server}/user/me

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #启用sql日志

#logging:
#  level:
#    root: debug